# As defined in the /.env file
development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

# As defined in the /.env file
test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
