development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  mailchimp_list_key: 'b02d8ce209'

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  mailchimp_list_key: 'b02d8ce209'

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  mailchimp_list_key: '9e843427cc'
